import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm";
const url=window.SUPABASE_URL;const key=window.SUPABASE_ANON_KEY;const loginArea=document.getElementById("login-area");const painelArea=document.getElementById("painel-area");const btnLogin=document.getElementById("btn-login");const btnSair=document.getElementById("btn-sair");const form=document.getElementById("form-produto");const listaAdmin=document.getElementById("lista-admin");let supabase=null;let produtos=[];
if(url&&key){supabase=createClient(url,key)}else{alert("Você ainda precisa configurar SUPABASE_URL e SUPABASE_ANON_KEY no arquivo config.js.")}
async function checarSessao(){if(!supabase)return;const{data}=await supabase.auth.getSession();if(data.session){loginArea.classList.add("oculto");painelArea.classList.remove("oculto");carregarProdutos()}}
btnLogin.addEventListener("click",async()=>{if(!supabase)return;const email=document.getElementById("email").value;const senha=document.getElementById("senha").value;const{error}=await supabase.auth.signInWithPassword({email,password:senha});if(error){alert("Erro ao entrar. Confira e-mail e senha.");return}loginArea.classList.add("oculto");painelArea.classList.remove("oculto");carregarProdutos()});
btnSair.addEventListener("click",async()=>{await supabase.auth.signOut();location.reload()});
async function uploadFoto(file){if(!file)return"";const nomeArquivo=`${Date.now()}-${file.name}`.replaceAll(" ","-");const caminho=`armacoes/${nomeArquivo}`;const{error}=await supabase.storage.from("produtos").upload(caminho,file,{upsert:true});if(error){alert("Erro ao enviar foto.");return""}const{data}=supabase.storage.from("produtos").getPublicUrl(caminho);return data.publicUrl}
form.addEventListener("submit",async(e)=>{e.preventDefault();const id=document.getElementById("produto-id").value;const file=document.getElementById("foto").files[0];let imagem_url="";if(file)imagem_url=await uploadFoto(file);const payload={nome:document.getElementById("nome").value,categoria:document.getElementById("categoria-produto").value,descricao:document.getElementById("descricao").value,preco:document.getElementById("preco").value||"Consulte",destaque:document.getElementById("destaque").checked,ativo:true};if(imagem_url)payload.imagem_url=imagem_url;let result=id?await supabase.from("produtos").update(payload).eq("id",id):await supabase.from("produtos").insert(payload);if(result.error){alert("Erro ao salvar armação.");return}form.reset();document.getElementById("produto-id").value="";carregarProdutos();alert("Armação salva com sucesso!")});
async function carregarProdutos(){const{data,error}=await supabase.from("produtos").select("*").order("created_at",{ascending:false});if(error){listaAdmin.innerHTML="<p>Erro ao carregar produtos.</p>";return}produtos=data||[];renderizarAdmin()}
function renderizarAdmin(){if(!produtos.length){listaAdmin.innerHTML="<p>Nenhuma armação cadastrada ainda.</p>";return}listaAdmin.innerHTML=produtos.map(p=>`<div class="admin-item">${p.imagem_url?`<img src="${p.imagem_url}" alt="${p.nome}">`:`<div class="semfoto">Sem foto</div>`}<div><strong>${p.nome}</strong><p>${p.categoria} • ${p.preco||"Consulte"}</p></div><div><button class="editar" data-id="${p.id}">Editar</button><button class="excluir" data-id="${p.id}">Excluir</button></div></div>`).join("");document.querySelectorAll(".editar").forEach(btn=>btn.addEventListener("click",()=>editar(btn.dataset.id)));document.querySelectorAll(".excluir").forEach(btn=>btn.addEventListener("click",()=>excluir(btn.dataset.id)))}
function editar(id){const p=produtos.find(item=>String(item.id)===String(id));if(!p)return;document.getElementById("produto-id").value=p.id;document.getElementById("nome").value=p.nome;document.getElementById("categoria-produto").value=p.categoria;document.getElementById("descricao").value=p.descricao;document.getElementById("preco").value=p.preco||"";document.getElementById("destaque").checked=!!p.destaque;window.scrollTo({top:0,behavior:"smooth"})}
async function excluir(id){if(!confirm("Deseja remover esta armação?"))return;const{error}=await supabase.from("produtos").update({ativo:false}).eq("id",id);if(error){alert("Erro ao excluir.");return}carregarProdutos()}
checarSessao();
